name: unpaprd
description: An open source audiobook player.
version: 2.2.0+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: 0.13.2
  http:
  google_fonts:
  transparent_image:
  cached_network_image:
  mobx:
  flutter_mobx:
  provider:
  connectivity:
  shared_preferences:
  flutter_pdfview:
  path_provider:
  flutter_icons:
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: assets/icon.png
  android: true
  ios: true
